var rtn = [
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1026114","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "5317","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1026114"},
    {"SBC_CVE_N": "199","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "PANTUFLA SUECO","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "73","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "5157","ULT_SUST_DEF": "1115718","MAR_DESC_STR": "HEVA SHOES","AR_ESTILO_STR": "4013","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "PANTUFLA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1115718"},
    {"SBC_CVE_N": "199","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "PANTUFLA SUECO","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "73","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "5157","ULT_SUST_DEF": "1115719","MAR_DESC_STR": "HEVA SHOES","AR_ESTILO_STR": "4011","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "PANTUFLA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1115719"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "4686","ULT_SUST_DEF": "1151085","MAR_DESC_STR": "NEW YORK GROUP","AR_ESTILO_STR": "S038","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1116855"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "4686","ULT_SUST_DEF": "1151086","MAR_DESC_STR": "NEW YORK GROUP","AR_ESTILO_STR": "S038","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1116856"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "7690","ULT_SUST_DEF": "1123511","MAR_DESC_STR": "NUWAY","AR_ESTILO_STR": "OSO5","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1123511"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "AMARILLO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "4683","ULT_SUST_DEF": "1126099","MAR_DESC_STR": "ROENARI","AR_ESTILO_STR": "1515","CA_CVE_N": "1858","COL_CVE_N": "2021","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1126099"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "4684","ULT_SUST_DEF": "1139752","MAR_DESC_STR": "BIG FINGER","AR_ESTILO_STR": "QT61","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139752"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "4684","ULT_SUST_DEF": "1139753","MAR_DESC_STR": "BIG FINGER","AR_ESTILO_STR": "QT61","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139753"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1151085","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "S038","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1151085"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "2_3_4","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "UE","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "3","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1151086","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "S038","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1151086"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "4","SEC_CVE_N": "5","MAR_CVE_N": "8484","ULT_SUST_DEF": "1126566","MAR_DESC_STR": "H-SUNSHINE","AR_ESTILO_STR": "HSP5","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1126566"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "8902","ULT_SUST_DEF": "1112461","MAR_DESC_STR": "XINGSHUNDA SHOES","AR_ESTILO_STR": "89A5","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1112461"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "NIÑA B SAND DEPORTIVA CERRADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3507","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "8902","ULT_SUST_DEF": "1112462","MAR_DESC_STR": "XINGSHUNDA SHOES","AR_ESTILO_STR": "9016","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1112462"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "NIÑA B SAND DEPORTIVA CERRADA","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3507","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "8902","ULT_SUST_DEF": "1112463","MAR_DESC_STR": "XINGSHUNDA SHOES","AR_ESTILO_STR": "9016","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1112463"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1114704","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "3180","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114704"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "3254","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "5349","ULT_SUST_DEF": "1114721","MAR_DESC_STR": "PRETTY SHOES","AR_ESTILO_STR": "J001","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114721"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "CAFE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "8566","ULT_SUST_DEF": "1137209","MAR_DESC_STR": "FONERAYA","AR_ESTILO_STR": "0601","CA_CVE_N": "1858","COL_CVE_N": "382","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1137209"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "8566","ULT_SUST_DEF": "1137210","MAR_DESC_STR": "FONERAYA","AR_ESTILO_STR": "0602","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1137210"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "NIÑA B SAND DEPORTIVA CERRADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3507","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "4985","ULT_SUST_DEF": "1139614","MAR_DESC_STR": "BANU","AR_ESTILO_STR": "1616","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139614"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25","FPLG_DESC_STR": "NIÑA B SAND DEPORTIVA CERRADA","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3507","CONS_CVE_N": "5","SEC_CVE_N": "5","MAR_CVE_N": "4985","ULT_SUST_DEF": "1139615","MAR_DESC_STR": "BANU","AR_ESTILO_STR": "1617","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139615"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND KIT PISO SUECO","DIV_CVE_N": "1","COL_DESC_STR": "ROSA/NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "259","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5349","ULT_SUST_DEF": "829572","MAR_DESC_STR": "PRETTY SHOES","AR_ESTILO_STR": "4605","CA_CVE_N": "1858","COL_CVE_N": "5084","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "829572"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT VALVULA BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2879","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4985","ULT_SUST_DEF": "985702","MAR_DESC_STR": "BANU","AR_ESTILO_STR": "86Y6","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "985702"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "MARINO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "268","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5607","ULT_SUST_DEF": "992250","MAR_DESC_STR": "D´GRIS","AR_ESTILO_STR": "022","CA_CVE_N": "1858","COL_CVE_N": "2534","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "992250"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT VALVULA PESCADOR","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2877","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4985","ULT_SUST_DEF": "1017835","MAR_DESC_STR": "BANU","AR_ESTILO_STR": "8586","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1017835"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON TRACK BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2418","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8261","ULT_SUST_DEF": "1033186","MAR_DESC_STR": "PEDRO DI VIANI","AR_ESTILO_STR": "3215","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1033186"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND KIT PISO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "LADRILLO/NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "198","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4867","ULT_SUST_DEF": "1033927","MAR_DESC_STR": "INSPIRACION","AR_ESTILO_STR": "4122","CA_CVE_N": "1858","COL_CVE_N": "10530","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1033927"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND TACON ALTO ANCHO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "NARANJA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "58","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4601","ULT_SUST_DEF": "1057975","MAR_DESC_STR": "JP ORIGINAL","AR_ESTILO_STR": "LD06","CA_CVE_N": "1858","COL_CVE_N": "619","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1057975"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT ALTO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "FIUSHA","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "232","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4601","ULT_SUST_DEF": "1057977","MAR_DESC_STR": "JP ORIGINAL","AR_ESTILO_STR": "EN28","CA_CVE_N": "1858","COL_CVE_N": "500","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1057977"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT MEDIO TALON C/PULS","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "290","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5623","ULT_SUST_DEF": "1060279","MAR_DESC_STR": "ESTEP","AR_ESTILO_STR": "5833","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1060279"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT MED TALON C/P","DIV_CVE_N": "1","COL_DESC_STR": "AMARILLO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1099","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8484","ULT_SUST_DEF": "1060547","MAR_DESC_STR": "H-SUNSHINE","AR_ESTILO_STR": "3010","CA_CVE_N": "1858","COL_CVE_N": "2021","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1060547"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT ALTO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "PLATA","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "232","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4556","ULT_SUST_DEF": "1061132","MAR_DESC_STR": "LEGEND","AR_ESTILO_STR": "EL01","CA_CVE_N": "1858","COL_CVE_N": "810","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061132"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND OC ESP CUÑA","DIV_CVE_N": "1","COL_DESC_STR": "PLATA","CURSOR": "1","CAT_CVE_N": "50","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "OCASIONES ESPECIALES","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1989","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4556","ULT_SUST_DEF": "1061133","MAR_DESC_STR": "LEGEND","AR_ESTILO_STR": "E20","CA_CVE_N": "1858","COL_CVE_N": "810","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061133"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT ANCHO AMARRE","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3018","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4556","ULT_SUST_DEF": "1061136","MAR_DESC_STR": "LEGEND","AR_ESTILO_STR": "IA32","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061136"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT ANCHO AMARRE","DIV_CVE_N": "1","COL_DESC_STR": "FIUSHA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3018","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4556","ULT_SUST_DEF": "1061137","MAR_DESC_STR": "LEGEND","AR_ESTILO_STR": "IA32","CA_CVE_N": "1858","COL_CVE_N": "500","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061137"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CUÑA ALTO ROMANO","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2886","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061402","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "3925","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061402"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CUÑA ALTO ROMANO","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2886","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061403","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "1192","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061403"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CUÑA ALTO TALON C/PULS","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "239","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061404","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "9212","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061404"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND KIT CONFORT","DIV_CVE_N": "1","COL_DESC_STR": "ROSA/COGÑAC","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1078","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8321","ULT_SUST_DEF": "1061436","MAR_DESC_STR": "PORT LAND","AR_ESTILO_STR": "5126","CA_CVE_N": "1858","COL_CVE_N": "23896","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061436"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT VALVULA PESCADOR","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2877","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4985","ULT_SUST_DEF": "1063839","MAR_DESC_STR": "BANU","AR_ESTILO_STR": "8286","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1063839"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CUÑA MEDIO TALON C/PULS","DIV_CVE_N": "1","COL_DESC_STR": "ROJO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "267","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4556","ULT_SUST_DEF": "1064232","MAR_DESC_STR": "LEGEND","AR_ESTILO_STR": "IE18","CA_CVE_N": "1858","COL_CVE_N": "825","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1064232"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4914","ULT_SUST_DEF": "1083820","MAR_DESC_STR": "XIA BELLA","AR_ESTILO_STR": "8043","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1083820"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "268","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5607","ULT_SUST_DEF": "1083934","MAR_DESC_STR": "D´GRIS","AR_ESTILO_STR": "025","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1083934"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MED PLAT MUY ANCHO TAL CP","DIV_CVE_N": "1","COL_DESC_STR": "NEUTRO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "3020","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5515","ULT_SUST_DEF": "1119937","MAR_DESC_STR": "CALZADO SENSASHION","AR_ESTILO_STR": "4131","CA_CVE_N": "1858","COL_CVE_N": "1493","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1084076"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8553","ULT_SUST_DEF": "1084096","MAR_DESC_STR": "TAO","AR_ESTILO_STR": "G070","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1084096"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1834","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8825","ULT_SUST_DEF": "1112460","MAR_DESC_STR": "TOPLANT","AR_ESTILO_STR": "4154","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1112460"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT CHUNKY TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3253","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8510","ULT_SUST_DEF": "1112486","MAR_DESC_STR": "FUQUIDE","AR_ESTILO_STR": "4070","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1112486"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT SUELA COR TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2884","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5632","ULT_SUST_DEF": "1114234","MAR_DESC_STR": "SIRENA","AR_ESTILO_STR": "3107","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114234"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT TACON PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3011","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4683","ULT_SUST_DEF": "1114629","MAR_DESC_STR": "ROENARI","AR_ESTILO_STR": "0824","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114629"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "VESTIR MOCASIN C/HERRAJE","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3502","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1114705","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "Y010","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114705"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "VESTIR MOCASIN C/HERRAJE","DIV_CVE_N": "1","COL_DESC_STR": "CAFE","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3502","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1114706","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "Y010","CA_CVE_N": "1858","COL_CVE_N": "382","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114706"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "VESTIR MOCASIN C/HERRAJE","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3502","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5257","ULT_SUST_DEF": "1114707","MAR_DESC_STR": "ONLEAD","AR_ESTILO_STR": "Y010","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1114707"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON TRACK TRABAT","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2420","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8473","ULT_SUST_DEF": "1115489","MAR_DESC_STR": "HANHAO","AR_ESTILO_STR": "H21S","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1115489"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND KIT CONFORT","DIV_CVE_N": "1","COL_DESC_STR": "ORO/NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1078","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "7751","ULT_SUST_DEF": "1116382","MAR_DESC_STR": "KOW LOON","AR_ESTILO_STR": "M800","CA_CVE_N": "1858","COL_CVE_N": "5988","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1116382"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "LILA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5632","ULT_SUST_DEF": "1117984","MAR_DESC_STR": "SIRENA","AR_ESTILO_STR": "7203","CA_CVE_N": "1858","COL_CVE_N": "535","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1117984"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MED PLAT MUY ANCHO TAL CP","DIV_CVE_N": "1","COL_DESC_STR": "NEUTRO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "3020","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "1391","ULT_SUST_DEF": "1119937","MAR_DESC_STR": "DAMAS","AR_ESTILO_STR": "4131","CA_CVE_N": "1858","COL_CVE_N": "1493","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1119937"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO TIPO CROCS","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "717","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5132","ULT_SUST_DEF": "1134322","MAR_DESC_STR": "HR","AR_ESTILO_STR": "B806","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1134322"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND CONFORT CUÑA DESTALONADO","DIV_CVE_N": "1","COL_DESC_STR": "MAQUILLAJE","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1829","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "4480","ULT_SUST_DEF": "1134324","MAR_DESC_STR": "KANDY LIVE","AR_ESTILO_STR": "6205","CA_CVE_N": "1858","COL_CVE_N": "7244","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1134324"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PANTUFLA","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "242","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "7690","ULT_SUST_DEF": "1134769","MAR_DESC_STR": "NUWAY","AR_ESTILO_STR": "DOG2","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1134769"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PANTUFLA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "242","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "7690","ULT_SUST_DEF": "1134770","MAR_DESC_STR": "NUWAY","AR_ESTILO_STR": "ABIT","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1134770"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "3061","ULT_SUST_DEF": "1136132","MAR_DESC_STR": "STARS","AR_ESTILO_STR": "8722","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136132"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON TALON C/PULS","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "263","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5616","ULT_SUST_DEF": "1136229","MAR_DESC_STR": "MY PRINCESS","AR_ESTILO_STR": "1157","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136229"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "MARINO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "54","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "1349","ULT_SUST_DEF": "1136230","MAR_DESC_STR": "MALBREY","AR_ESTILO_STR": "1626","CA_CVE_N": "1858","COL_CVE_N": "2534","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136230"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT BAJO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "301","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "3426","ULT_SUST_DEF": "1136236","MAR_DESC_STR": "PRETTY","AR_ESTILO_STR": "4589","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136236"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT BAJO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "LATTE","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "723","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "3426","ULT_SUST_DEF": "1136237","MAR_DESC_STR": "PRETTY","AR_ESTILO_STR": "4590","CA_CVE_N": "1858","COL_CVE_N": "23239","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136237"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO CHUNKY","DIV_CVE_N": "1","COL_DESC_STR": "FIUSHA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3254","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "5077","ULT_SUST_DEF": "1136861","MAR_DESC_STR": "GREEN BOX","AR_ESTILO_STR": "0802","CA_CVE_N": "1858","COL_CVE_N": "500","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1136861"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "MAPLE","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "256","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8942","ULT_SUST_DEF": "1137572","MAR_DESC_STR": "TACUBA SHOES","AR_ESTILO_STR": "002","CA_CVE_N": "1858","COL_CVE_N": "1044","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1137572"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND KIT TACON PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO/MAGNOLIA","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "2010","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8720","ULT_SUST_DEF": "1138972","MAR_DESC_STR": "PUNTO MODA","AR_ESTILO_STR": "672","CA_CVE_N": "1858","COL_CVE_N": "24572","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1138972"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT MEDIO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "1908","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8720","ULT_SUST_DEF": "1138973","MAR_DESC_STR": "PUNTO MODA","AR_ESTILO_STR": "34","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1138973"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON ROMANO","DIV_CVE_N": "1","COL_DESC_STR": "MAQUILLAJE","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "1991","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8720","ULT_SUST_DEF": "1138974","MAR_DESC_STR": "PUNTO MODA","AR_ESTILO_STR": "117","CA_CVE_N": "1858","COL_CVE_N": "7244","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1138974"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON ROMANO","DIV_CVE_N": "1","COL_DESC_STR": "CIELO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "1991","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "8720","ULT_SUST_DEF": "1138975","MAR_DESC_STR": "PUNTO MODA","AR_ESTILO_STR": "117","CA_CVE_N": "1858","COL_CVE_N": "459","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1138975"},
    {"SBC_CVE_N": "287","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "ZAP PUNTAL TACON ALTO DELGADO","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "2","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "PUNTAL","FPLG_CVE_N": "616","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "7990","ULT_SUST_DEF": "1139480","MAR_DESC_STR": "TIANCHEN","AR_ESTILO_STR": "5188","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "ZAPATILLA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139480"},
    {"SBC_CVE_N": "287","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "23_24_25_26","FPLG_DESC_STR": "ZAP PUNTAL TACON ALTO DELGADO","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "2","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "PUNTAL","FPLG_CVE_N": "616","CONS_CVE_N": "6","SEC_CVE_N": "5","MAR_CVE_N": "7990","ULT_SUST_DEF": "1139481","MAR_DESC_STR": "TIANCHEN","AR_ESTILO_STR": "5188","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "ZAPATILLA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1139481"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "ORO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "985696","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "TWS1","CA_CVE_N": "1858","COL_CVE_N": "801","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "985696"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND KIT SUELA CORRIDA MEDIO","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO/NUTTY","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2892","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "3055","ULT_SUST_DEF": "991376","MAR_DESC_STR": "LADIES D´VALERIA","AR_ESTILO_STR": "203","CA_CVE_N": "1858","COL_CVE_N": "10941","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "991376"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND KIT PISO HORCAPOLLO","DIV_CVE_N": "1","COL_DESC_STR": "ORO ROSA/CAMEL","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "205","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "7862","ULT_SUST_DEF": "992511","MAR_DESC_STR": "CELINNE","AR_ESTILO_STR": "1865","CA_CVE_N": "1858","COL_CVE_N": "23523","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "992511"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1017857","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "TWS5","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1017857"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "BEIGE","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1017858","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "TWS3","CA_CVE_N": "1858","COL_CVE_N": "366","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1017858"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1017859","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "TWS4","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1017859"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND SUELA CORR BAJO YUTE TALO","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2930","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1017953","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "9030","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1017953"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON MEDIO ANCHO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NARANJA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "90","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1050992","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "7015","CA_CVE_N": "1858","COL_CVE_N": "619","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1024767"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND PLAT C/TACON PINT TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "TABACO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2410","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8391","ULT_SUST_DEF": "1034133","MAR_DESC_STR": "MHANDALA SHOES","AR_ESTILO_STR": "3205","CA_CVE_N": "1858","COL_CVE_N": "861","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1034133"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON MEDIO ANCHO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NARANJA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "90","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "395","ULT_SUST_DEF": "1050992","MAR_DESC_STR": "PIETRO ALESSANDRO","AR_ESTILO_STR": "7015","CA_CVE_N": "1858","COL_CVE_N": "619","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1050992"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND KIT CONFORT","DIV_CVE_N": "1","COL_DESC_STR": "BEIGE/NEGRO","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1078","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8321","ULT_SUST_DEF": "1058156","MAR_DESC_STR": "PORT LAND","AR_ESTILO_STR": "5057","CA_CVE_N": "1858","COL_CVE_N": "4890","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1058156"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND PLAYA BAÑO PREMOLDEADA","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "241","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5632","ULT_SUST_DEF": "1058167","MAR_DESC_STR": "SIRENA","AR_ESTILO_STR": "0304","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1058167"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "NIÑA B SAND DEPORTIVA CERRADA","DIV_CVE_N": "1","COL_DESC_STR": "ROSA","CURSOR": "1","CAT_CVE_N": "54","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "PLAYA/BAÑO","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "3507","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5661","ULT_SUST_DEF": "1058173","MAR_DESC_STR": "PANTHINK","AR_ESTILO_STR": "3312","CA_CVE_N": "1858","COL_CVE_N": "839","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1058173"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1060569","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "6617","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1060569"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND PLAT ALTO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "NEGRO","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "219","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1105598","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "2057","CA_CVE_N": "1858","COL_CVE_N": "4970","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061405"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON MEDIO ANCHO ROMANO","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "74","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061407","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "06H2","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061407"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON ALTO ANCHO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "FIUSHA","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "58","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061411","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "0343","CA_CVE_N": "1858","COL_CVE_N": "500","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061411"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON BAJO ANCHO PULSERA","DIV_CVE_N": "1","COL_DESC_STR": "CORAL","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "1","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "CUADRADA","FPLG_CVE_N": "63","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061417","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "8113","CA_CVE_N": "1858","COL_CVE_N": "1515","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061417"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT MEDIO BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "TAN","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "103","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061420","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "79B1","CA_CVE_N": "1858","COL_CVE_N": "876","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061420"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT MEDIO BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "BLANCO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "103","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "8308","ULT_SUST_DEF": "1061424","MAR_DESC_STR": "MARBURY","AR_ESTILO_STR": "1672","CA_CVE_N": "1858","COL_CVE_N": "2179","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1061424"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND TACON MEDIO ANCHO BOTIN","DIV_CVE_N": "1","COL_DESC_STR": "AZUL","CURSOR": "1","CAT_CVE_N": "12","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CASUAL","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "70","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5622","ULT_SUST_DEF": "1062544","MAR_DESC_STR": "ANLI FOOTWEAR","AR_ESTILO_STR": "5089","CA_CVE_N": "1858","COL_CVE_N": "19","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1062544"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND MEDIA PLAT MED TALON C/P","DIV_CVE_N": "1","COL_DESC_STR": "ROJO","CURSOR": "1","CAT_CVE_N": "83","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "VESTIR","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1099","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5622","ULT_SUST_DEF": "1062549","MAR_DESC_STR": "ANLI FOOTWEAR","AR_ESTILO_STR": "0268","CA_CVE_N": "1858","COL_CVE_N": "825","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1062549"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "BRONCE","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1063842","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "WS14","CA_CVE_N": "1858","COL_CVE_N": "376","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1063842"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO TRABA T","DIV_CVE_N": "1","COL_DESC_STR": "PLATA","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "1837","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1063843","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "WS15","CA_CVE_N": "1858","COL_CVE_N": "810","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1063843"},
    {"SBC_CVE_N": "244","FEC_ITI_DT":"05/10/2023","EQR_TA_STR": "22_23_24_25_26","FPLG_DESC_STR": "SAND CONFORT PISO PESCADOR","DIV_CVE_N": "1","COL_DESC_STR": "CAMEL","CURSOR": "1","CAT_CVE_N": "17","HOR_CVE_N": "3","CO_CVE_STR": "U5","CUCS_CVE_N": "70","CAT_DESC_STR": "CONFORT","HOR_DESC_STR": "REDONDA","FPLG_CVE_N": "2005","CONS_CVE_N": "7","SEC_CVE_N": "5","MAR_CVE_N": "5625","ULT_SUST_DEF": "1063845","MAR_DESC_STR": "CALIDA","AR_ESTILO_STR": "WS11","CA_CVE_N": "1858","COL_CVE_N": "1368","SBC_DESC_STR": "SANDALIA","CA_DESC_STR": "SANDALIAS | 2024 | 1E","DIV_DESC_STR": "CALZADO","SEC_DESC_STR": "DAMA","ID_ART": "1063845"}];
var diving = {
    subGp: function(arr, p) {
        return this.group(arr.items, p);
    },
    group:function(a, p) {
        var rtn = [];
        var nar = [];
        var sx = false;
        p=(p.length)?p:[p];
        for (var x = 0; x < p.length; x++) {
            a=(nar.length>0)?nar:a;
            for (var y = 0; y < a.length; y++) {
                if (a[y].items) {
                    a[y].items = diving.subGp(a[y], [p[x]]);
                    sx = true;
                } else {
                    var itm = {};
                    itm = {
                        field: p[x].field,
                        value: a[y][p[x].field],
                        items: [a[y]]
                    };
                    if (nar.length == 0) {
                        nar.push(itm);
                    } else {
                        var ex = false;
                        var itms = 0;
                        for (var z = 0; z < nar.length; z++) {
                            if ((nar[z].field == itm.field) && (nar[z].value == itm.value)) {
                                ex = true;
                                itms = z;
                                break;
                            }
                        }
                        if (!ex) {
                            nar.push(itm);
                        } else {
                            nar[itms].items.push(itm.items[0]);
                        }
                    }
                }
            }
            if (!sx) {
                rtn = nar;
            }
        }
        if (!sx)
            a = rtn;
        return a;
    },
    widget: function (w) {
        var obj = {name: 'div' + w.name || null};
        if (!obj.name)
            return;
        var fun = $.fn[obj.name] = w || {};
        $.extend($.ui, {[obj.name]: fun});
        $.fn[obj.name] = w.init;
    }
};
     window.diving = dvn=diving;

class Source{
     constructor(p){
          if(p.schema){
               this.options=this.options||{};
               this.options.schema=p.schema||{};
               this.options.schema.model=(p.schema)?p.schema.model||{}:{};
               this.options.schema.model.fields=(p.schema)?(p.schema.model)?p.schema.model.fields||{}:{}:{};
          }
          this.setData(p.data);
          if(p.group){
               this.grupo = p.group;
          }
          if(p.sort){
               this.sort(p.sort);
          }
          (p.group)?this.group(p.group):null;
          if(p.aggregate){
               this.aggregate(p.aggregate,this.options);
          }
          return this;
     }
     aggregate(a,c){
          var ts = this;
          var b = null;
          if(c.hasOwnProperty('data')){
               if(c.data[0].hasOwnProperty('items'))
                    for(var x=0;x<c.data.length;x++)
                         ts.aggregate(a,c.data[x].items);
               else
               	b=c.data;
          }else{
               b=c;
          }
          if(b!=null)
          Object.keys(a).map(function(k){
               var s = 0;
               b.map(function(d){s+=d[a[k].field];});
               switch(k){
                    case 'sum':b.map(function(d){d['aggregate_'+k]=s;});break;
                    case 'avg':b.map(function(d){d['aggregate_'+k]=d[a[k].field]/s;});break;
               }
          });
     }
     setData(data){
        var temporalDts = [];
        $.each(data,function(i,v){
            temporalDts.push(v);
        });
          this.options=this.options||{};
          if(this.options.hasOwnProperty('schema')){
               if(this.options.schema.hasOwnProperty('model')){
                    if(this.options.schema.model.hasOwnProperty('fields')){
                         var opFields = this.options.schema.model.fields;
                       var fields = Object.keys(opFields);
                         $.each(temporalDts,function(i,v){
							$.each(fields,function(f,k){
                                 if(opFields[k].type=='number'){
                                      v[k]=parseFloat(v[k]);
                                 }
                                 if(opFields[k].type=='date'){
                                      v[k]=new Date(v[k]);
                                 }
                                 if(opFields[k].type=='string'){
                                      v[k]=""+v[k];
                                 }
                            });
                         });
                    }
               }
          }
          this.options.data=temporalDts;
     }
     view(){
          return this.options.data;
     }
     group(p){
          var elements=this.options.data;
          this.options.data=diving.group(elements,p);
     }
     sort(orden){
          var srt = (!Array.isArray(orden))?[orden]:orden;
          var elements = this.options.data;
          $.each(srt,function(i,v){
               var sort = v.field;
               var dir = (v.dir)?(v.dir==='desc')?-1:v.dir:1;
               elements.sort(function(a,b){
                    if(eval('a[sort]'+((dir===1)?'>':'<')+'b[sort]')){
                         return 1;
                    }
                    if(eval('a[sort]'+((dir==-1)?'>':'<')+'b[sort]')){
                         return -1;
                    }
                    return 1;
               });
          });
     }
}
diving.data = diving.data || {};
diving.store = diving.store || {};

diving.data.DataSource = Source;
diving.store.Source = Source;


var dts = new dvn.data.DataSource({
     data:rtn,
     //sort:{field: 'FPLG_DESC_STR',str:'desc'},
     //group:[{field: 'SBC_CVE_N'},{field:'EQR_TA_STR'}],
     schema:{
          model:{
               fields:{
                    FEC_ITI_DT:   {type: 'date'   },
                    SBC_CVE_N:    {type: 'number' },
                    EQR_TA_STR:   {type: 'string' },
                    FPLG_DESC_STR:{type: 'string' },
                    DIV_CVE_N:    {type: 'number' },
                    COL_DESC_STR: {type: 'string' },
                    CURSOR:       {type: 'number' },
                    CAT_CVE_N:    {type: 'number' },
                    HOR_CVE_N:    {type: 'number' },
                    CO_CVE_STR:   {type: 'string' },
                    CUCS_CVE_N:   {type: 'number' },
                    CAT_DESC_STR: {type: 'string' },
                    HOR_DESC_STR: {type: 'string' },
                    FPLG_CVE_N:   {type: 'number' },
                    CONS_CVE_N:   {type: 'number' },
                    SEC_CVE_N:    {type: 'number' },
                    MAR_CVE_N:    {type: 'number' },
                    ULT_SUST_DEF: {type: 'number' },
                    MAR_DESC_STR: {type: 'string' },
                    AR_ESTILO_STR:{type: 'string' },
                    CA_CVE_N:     {type: 'number' },
                    COL_CVE_N:    {type: 'number' },
                    SBC_DESC_STR: {type: 'string' },
                    CA_DESC_STR:  {type: 'string' },
                    DIV_DESC_STR: {type: 'string' },
                    SEC_DESC_STR: {type: 'string' },
                    ID_ART:       {type: 'number' }
               }
          }
     }
});

//console.log( dts.view() );
/*Boton*/
(function() {
    var widget = {
        name: "Button",
        init: function(prm) {
            prm = $.extend(prm, {
                text: prm.text || $(this)[0].innerHTML || '',
                classParent:"d-button",
                class: 'btn btn-'+((prm.type) ? prm.type : 'default') + ((prm.class) ? ' ' + prm.class : ''),
                type: (prm.type) ? prm.type : 'default'
            });
            var widtgetData = {
                setText: function(t) {
                    $($(this.elem).find('button')).text(t);
                    this.text = t;
                },
                destroy:function(){
                    $(this.elem).removeData('divNotification');
                    $(this.elem)[0].remove();
                },
                enabled:function(e){
                    var elemento = $(this.elem).data('divButton').elem;
                    $($(elemento).find('button')).attr('type',(e?this.type:'disabled'));
                },
                elem:$(this)[0]
            };
            widget.createElement(prm,widtgetData);
            $(this).data('div'+widget.name, widtgetData);
        },
        createElement: function(p,data) {
            $(data.elem).empty();
            var attributes = $.extend(p, {
                text: p.text,
                class: p.class,
                type: p.type
            });
            $(data.elem).addClass(p.classParent);
            delete attributes.classParent;
            var elemento = $('<button>', attributes);
            (p.type == 'disabled') ? elemento[0].onclick = function(event) {
                event.preventDefault();
            }: null;
            (p.icon) ? elemento[((typeof p.icon === 'string') ? 'append' : ((p.icon.pos == 'before') ? 'prepend' : 'append'))]($('<em>', {
                class: (typeof p.icon === 'string') ? p.icon : p.icon.class
            })): null;
            $(data.elem).append(elemento);
            $.extend(data,attributes);
        }
    };
    diving.widget(widget);
})();
/*TabsTrip*/
(function(){
    var widget = {
        name: "TabsTrip",
        init: function(prm) {
            prm=$.extend(prm,{class:"d-tabstrip"});
            var widtgetData = {
                elem:$(this)[0]
            };
            widget.createElement(prm,widtgetData);
            $(this).data('div'+widget.name, widtgetData);
        },
        createElement: function(p,data) {
            $(data.elem).empty();
            var wdt=this;
            var ttl = $('<ul>',{class:'nav nav-tabs',role:'tablist',id:$(data.elem).attr('id')+'_tab'});
            var cnt = $('<div>',{class:'tab-content'});
            $(data.elem).append(ttl).append(cnt);
            $.each(p.content,function(i,v){
                wdt.add(ttl,cnt,i,v);
            });
            var fstTbEl = document.querySelector( '#'+ $($(data.elem).find('ul')[0]).attr('id')+' li:first-child' );
            var fsTab = new bootstrap.Tab(fstTbEl);
            fsTab.show();
        },
        add:function(ttl,cnt,i,v){
            ttl.append(
                $('<li>',{class:'nav-item',role:'presentation'})
                .append(
                    $('<butto>',{
                        //id="home-tab" 
                        class:"nav-link"+(v.hasOwnProperty('open')?' active':''),
                        'data-bs-toggle':"tab",
                        'data-bs-target':"#"+v.id,
                        type:"button",
                        role:"tab",
                        'aria-controls':"tab-pane",
                        'aria-selected':"false",
                        text:v.title
                    })
                )
            );
            cnt.append(
                $('<div>',{
                    class:'tab-pane'+(v.hasOwnProperty('open')?' active':''),
                    id:v.id,
                    role:'tabpanel',
                    'arial-labelledby':'tab',
                    tabindex:i
                }).append(
                    v.element
                )
            );
        }
    };
    diving.widget(widget);
})();
/*MultiSelect*/
(function() {
    var widget = {
        name: "MultiSelect",
        init: function(prm) {
            prm = $.extend(prm, {
                classParent:"d-multiSelection",
                class: ((prm.type) ? 'd-' + prm.type : 'd-multi-selection') + ((prm.class) ? ' ' + prm.class : '')
            });
            var widtgetData = {
                enabled:function(e){
                    var e = $(this.elem).data('divMultiSelection').elem;
                    //$($(e).find('input')).attr('type',(e?this.type:'disabled'));
                },
                dataSource: prm.dataSource,
                dataTextField:prm.dataTextField||'',
                dataValueField:prm.dataValueField||'',
                elem:$(this)[0]
            };
            delete prm.dataSource;
            widget.createElement(prm,widtgetData);
            $(this).data('div'+widget.name, widtgetData);
        },
        createElement: function(p,data) {
            $(data.elem).empty();
            var wdt = this;
            var select = $('<select>',{class:"form-select",'aria-label':"Default select example"})//'aria-label':"Default select example", 
            select.change(function(e){
                console.log( e );
            });
            $(data.elem).addClass(p.class);
            var ulSelected = $('<ul>');
            $(data.elem).append(ulSelected).append(select);
            if(!data.dataSource.hasOwnProperty('options')){
                $.each(data.dataSource,function(i,v){
                    select.append( $('<option>',{value:v,text:v}));
                });
            }else{
                $.each(data.dataSource.options.data,function(i,v){
                    if(typeof v == 'string'){
                        select.append( $('<option>',{value:v,text:v}));
                    }else{
                        select.append( $('<option>',{value:v[data.dataValueField],text:v[data.dataTextField]}));
                    }
                });
            }
        },
        selecciono:function(e){
            console.log( e.target );
        }
    };
    diving.widget(widget);
})();

var dtsMulti = [];
$.each(rtn,function(i,v){
    dtsMulti.push({VALUE:v.COL_CVE_N,MENSAJE:v.COL_DESC_STR});
});
dtsMulti.sort(function(a,b){return a.VALUE - b.VALUE;});

var dtsMt = dtsMulti.filter(function(item, index, self) {
    return index === self.findIndex(function(t) {
        return t.VALUE === item.VALUE && t.MENSAJE === item.MENSAJE;
    });
});



$('#multiSelection').divMultiSelect({
    dataSource://['AZUL','BEIGE','BRONCE','CAFE','CIELO','FIUSHA','LILA','NARANJA','ORO','PLATA','ROJO','ROSA','TABACO']
        new dvn.data.DataSource({
            //data:['AZUL','BEIGE','BRONCE','CAFE','CIELO','FIUSHA','LILA','NARANJA','ORO','PLATA','ROJO','ROSA','TABACO']
            data: dtsMt
        }),
    dataTextField:'MENSAJE',
    dataValueField:'VALUE'
});








$('#btn1').divButton({text:'primary',type:'primary'});
$('#btn2').divButton({text:'secondary',type:'secondary'});
$('#btn3').divButton({text:'success',type:'success'});
$('#btn4').divButton({text:'danger',type:'danger'});
$('#btn5').divButton({text:'warning',type:'warning'});
$('#btn6').divButton({text:'info',type:'info'});
$('#btn7').divButton({text:'light',type:'light'});
$('#btn8').divButton({text:'dark',type:'dark'});
$('#btn9').divButton({text:'link',type:'link'});

var nrtn = [];
$.each(rtn,function(i,v){
    nrtn.push({VALUE:v.ID_ART,MENSAJE:v.ID_ART});
});
var dtsMs = new dvn.store.Source({
    data:nrtn,
    schema:{model:{fields:{VALUE:{type:'number'},MENSAJE:{type:'string'}}}}
});

//$('#division').divButton({
//    text:'hola',
//    click:function(){
//        alert( 'hola que tal' );
//    }
//});
//var divBoton = $('#division').data('divButton');
//console.log( divBoton );
$('#division').divTabsTrip({
        content:[
            {title: 'titulo 1', id:'elem_1', element: $('<div>',{text:'loopReplacer(match, start, end, snippet)'}),open: true},
            {title: 'titulo 2', id:'elem_2', element: $('<div>',{text:'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum, accusantium ut commodi. Eius laudantium facere ullam quasi voluptates dolorum, inventore assumenda, non, officia, maiores quisquam debitis? Voluptatem nulla perspiciatis voluptates omnis! Quia facere dolorum explicabo, dicta incidunt aspernatur repellat natus alias magni, minus maxime consequatur debitis quo vitae laborum impedit culpa distinctio unde dolorem ipsum consectetur? Eos ducimus quisquam rerum laborum eum, repellat, quod reiciendis nam ipsum officiis dolorum tempora perspiciatis illum corrupti, tempore voluptates autem ullam assumenda quas. Vero officia, saepe blanditiis labore, dolor, doloribus amet deserunt necessitatibus eius dolore, consequuntur corporis temporibus obcaecati! Voluptatibus eos recusandae alias dicta?'})},
            {title: 'titulo 3', id:'elem_3', element: $('<div>',{text:'estas en el contenido 5'})},
            {title: 'titulo 4', id:'elem_4', element: $('<div>',{text:'estas en el contenido 6'})},
            {title: 'titulo 5', id:'elem_5', element: $('<div>',{text:'estas en el contenido 7'})},
            {title: 'titulo 6', id:'elem_6', element: $('<div>',{text:'estas en el contenido 8'})},
            {title: 'titulo 7', id:'elem_7', element: $('<div>',{text:'estas en el contenido 9'})}
        ]
    });